In [1]:
import time
import numpy as np

In [2]:
x = np.random.random(100000000)

In [3]:
t1 = time.time()
sum(x)/len(x)
print(time.time()-t1)

40.8391649723053


In [4]:
t2 = time.time()
np.mean(x)
print(time.time()-t2)

0.2108445167541504


# numpy arrays

In [5]:
# We create a 1D ndarray that contains only integers
x = np.array([[1, 2, 3, 4, 5],[6,7, 3, 4, 5]])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [[1 2 3 4 5]
 [6 7 3 4 5]]


In [6]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (2, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [7]:
# We create a rank 1 ndarray that only contains strings
y = np.array(['Hello', 'World'])

# We print x
print()
print('y = ', y)
print()

# We print information about x
print('y has dimensions:', y.shape)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  ['Hello' 'World']

y has dimensions: (2,)
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: <U5


In [8]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


In [9]:
# We create a rank 1 ndarray that contains integers
i = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
o = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
p = np.array([1, 2.5, 4,'lkjll'])

# We print the dtype of each ndarray
print('The elements in i are of type:', i.dtype)
print('The elements in o are of type:', o.dtype)
print('The elements in p are of type:', p.dtype)

The elements in i are of type: int32
The elements in o are of type: float64
The elements in p are of type: <U32


In [10]:
xx = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.float64)

# We print x
print()
print('xx = ', xx)
print()
xx.dtype = np.int64
xx.dtype = np.float64
xx.dtype = np.int64
print(xx)
# We print the dtype x
print('The elements in xx are of type:', xx.dtype)


xx =  [1.5 2.2 3.7 4.  5.9]

[4609434218613702656 4612136378390124954 4615514078110652826
 4616189618054758400 4618328827877759386]
The elements in xx are of type: int64


In [11]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

In [12]:
yy = np.load('my_array.npy')
print('\n','yy = ',yy)
print('\n','yy is an object type = ',type(yy))
print('\n','yy elemenets data type = ',yy.dtype)



 yy =  [1 2 3 4 5]

 yy is an object type =  <class 'numpy.ndarray'>

 yy elemenets data type =  int32


In [13]:
# We create a 3 x 4 ndarray full of zeros. 
XX = np.zeros((3,4))

# We print XX
print()
print('XX = \n', XX)
print()

# We print information about XX
print('XX has dimensions:', XX.shape)
print('XX is an object of type:', type(XX))
print('The elements in XX are of type:', XX.dtype)


XX = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

XX has dimensions: (3, 4)
XX is an object of type: <class 'numpy.ndarray'>
The elements in XX are of type: float64


In [14]:
YY = np.ones((3,2),dtype = np.int64)

# We print YY
print()
print('YY = \n', YY)
print()

# We print information about YY
print('YY has dimensions:', YY.shape)
print('YY is an object of type:', type(YY))
print('The elements in YY are of type:', YY.dtype) 


YY = 
 [[1 1]
 [1 1]
 [1 1]]

YY has dimensions: (3, 2)
YY is an object of type: <class 'numpy.ndarray'>
The elements in YY are of type: int64


In [15]:
# We create a 2 x 3 ndarray full of fives. 
xy = np.full((2,3), 5,dtype = np.float64) 

# We print zy
print()
print('xy = \n', xy)
print()

# We print information about xy
print('xy has dimensions:', xy.shape)
print('xy is an object of type:', type(xy))
print('The elements in xy are of type:', xy.dtype) 


xy = 
 [[5. 5. 5.]
 [5. 5. 5.]]

xy has dimensions: (2, 3)
xy is an object of type: <class 'numpy.ndarray'>
The elements in xy are of type: float64


In [16]:
yX = np.eye(5)

# We print yX
print()
print('yX = \n', yX)
print()

# We print yX*5
print()
print('yX*5 = \n', 5*yX)
print()

# We print information about yX
print('yX has dimensions:', yX.shape)
print('yX is an object of type:', type(yX))
print('The elements in yX are of type:', yX.dtype)


yX = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


yX*5 = 
 [[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]

yX has dimensions: (5, 5)
yX is an object of type: <class 'numpy.ndarray'>
The elements in yX are of type: float64


In [17]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
Xyy = np.diag([10,20,30,50])

# We print Xyy
print()
print('Xyy = \n', Xyy)
print('The elements in yX are of type:', Xyy.dtype)
print()


Xyy = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]
The elements in yX are of type: int32



In [18]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
v = np.arange(0,10,3)

# We print the ndarray
print()
print('v = ', v)
print()

# We print information about the ndarray
print('v has dimensions:', v.shape)
print('v is an object of type:', type(v))
print('The elements in x are of type:', v.dtype) 


v =  [0 3 6 9]

v has dimensions: (4,)
v is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [19]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.

xc = np.linspace(0,27.8,10, endpoint = False)
xxc = np.linspace(0,25,10)
reshapped_xxc = xxc.reshape(2,5)

# We print the ndarray
print()
print('xc = ', xc)
print()
print('xxc = ', xxc)
print()
print('reshapped_xxc = \n', reshapped_xxc)
print()

# We print information about the ndarray
print('xc has dimensions:', xc.shape)
print('xc is an object of type:', type(xc))
print('The elements in xc are of type:', xc.dtype)


xc =  [ 0.    2.78  5.56  8.34 11.12 13.9  16.68 19.46 22.24 25.02]

xxc =  [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

reshapped_xxc = 
 [[ 0.          2.77777778  5.55555556  8.33333333 11.11111111]
 [13.88888889 16.66666667 19.44444444 22.22222222 25.        ]]

xc has dimensions: (10,)
xc is an object of type: <class 'numpy.ndarray'>
The elements in xc are of type: float64


In [30]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
r = np.random.random((3,3))
rr = np.random.randint(4,5,(2,3))
rrr = np.random.normal(0,2,(1000,1000))

# We print r
print()
print('r = \n', r)
print()
print('rr = \n', rr)
print()
print('rrr = \n', rrr)
print()

# We print information about X
print('r has dimensions:', r.shape)
print('r is an object of type:', type(r))
print('The elements in x are of type:', r.dtype)


r = 
 [[0.8216873  0.48069928 0.3220153 ]
 [0.16142093 0.2467995  0.30393086]
 [0.32850753 0.36561849 0.53496528]]

rr = 
 [[4 4 4]
 [4 4 4]]

rrr = 
 [[-1.27732731  1.66277065  2.92243005 ...  2.32224444 -1.78040293
   1.83913578]
 [ 2.37997099  2.52929125  4.15356709 ...  1.8524347  -3.55823325
  -0.1570333 ]
 [ 1.48152603 -1.98454168  1.7455017  ... -4.6305791   2.42763045
  -0.28665997]
 ...
 [-1.27560129 -0.71575799 -1.4918235  ...  1.75560478  1.27258319
  -2.89938975]
 [ 1.01411528  3.20158552  1.50415357 ...  0.70655045 -0.19239327
  -0.37402422]
 [-0.06594606 -3.05974559  0.30018842 ... -3.25976743 -3.6067442
   4.36934522]]

r has dimensions: (3, 3)
r is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [21]:
def solution(total_lambs):
    # Your code here
    
    temp_total_lambs = total_lambs
    
    maxi = []
    mini = []
    
    maxi.append(1)
    
    while temp_total_lambs > 0 and sum(maxi)+maxi[-1]*2 <= total_lambs:
        maxi.append(maxi[-1]*2)
        temp_total_lambs -= maxi[-1]
    
    
    mini.append(1)
    mini.append(1)
    
    temp_total_lambs = total_lambs
    while temp_total_lambs > 0 and sum(mini)+mini[-1]+mini[-2] <= total_lambs:
        mini.append(mini[-1]+mini[-2])
        temp_total_lambs -=mini[-1]
    
    return maxi, mini, len(mini) - len(maxi),sum(mini),sum(maxi)

In [22]:
solution(143)  #1,2,4,8,16,32,64.-->15 // #1,1,2,3,5,8,13,21,34,55

([1, 2, 4, 8, 16, 32, 64], [1, 1, 2, 3, 5, 8, 13, 21, 34, 55], 3, 143, 127)