In [1]:
import numpy as np

# Accessing Elements In ndarrays

## rank 1 ndarray - numpy

In [5]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

# Replace the forth element in the array with 20
x[3] = 20

# We print x after it was modified 
print('Modified x:\n x = ', x)


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5
Modified x:
 x =  [ 1  2  3 20  5]


## rank 2 ndarray - numpy

In [7]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print X
print()
print('X = \n', X)
print()

# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])

# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

# We print X after it was modified 
print('Modified:\n X = \n', X)


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9
Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Deleting Elements In ndarrays

In [29]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.arange(1,10).reshape(3,3)

# We print x
print()
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x, [0,4])

# We print x with the first and last element deleted
print()
print('Modified x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We delete the first column and last row of y
#n = np.delete(Y, 0, axis=1).(Y, 2, axis=0)
n = np.delete(np.delete(Y, [0,2],1),[0,2],0)


# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)

print()
print('n = \n', n)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]

n = 
 [[5]]


# Inserting Elements In ndarrays

In [41]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.arange(1,10).reshape(3,3)

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We print v
print()
print('v = \n', v)

# We append a new column containing 9 and 10 to y
q = np.append(v,[[10],[10],[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)

# We print Y
print()
print('Modefied Y = \n', Y)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]

q = 
 [[ 1  2  3 10]
 [ 4  5  6 10]
 [ 7  8  9  9]
 [ 7  8  9 10]]

Modefied Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[40,50,60],axis=0)

ww = np.insert(Y,-1,[40,50,60],axis=0)

www = np.insert(Y,len(Y),[40,50,60],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)

# We print w
print()
print('w = \n', w)

# We print ww
print()
print('ww = \n', ww)

# We print www
print()
print('www = \n', www)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[ 1  2  3]
 [40 50 60]
 [ 7  8  9]]

ww = 
 [[ 1  2  3]
 [40 50 60]
 [ 7  8  9]]

www = 
 [[ 1  2  3]
 [ 7  8  9]
 [40 50 60]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


In [64]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


In [133]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]


# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

R[0,0] = 5100
# We print R
print()
print('R = \n', R)

print()
print('Modified X = \n', X)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[5100]
 [   7]
 [  12]
 [  17]]

Modified X = 
 [[   0    1 5100    3    4]
 [   5    6    7    8    9]
 [  10   11   12   13   14]
 [  15   16   17   18   19]]


In [137]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print X
print()
print('X = \n', X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[[indices],:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

# We print Y
print()
print('Y = \n', Y)

# We print Z
print()
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]


Y = 
 [[[ 5  6  7  8  9]
  [15 16 17 18 19]]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [170]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5)
X[:,1]= 50
X[1,:]= 60
X[0,1] = 100
# We print X
print()
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('yy =', np.diag(X, 1))
print()

# We print the elements above*2 the main diagonal of X
print('y =', np.diag(X, 2))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, -1))

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[  0 100   2   3   4]
 [ 60  60  60  60  60]
 [ 10  50  12  13  14]
 [ 15  50  17  18  19]
 [ 20  50  22  23  24]]

z = [ 0 60 12 18 24]

yy = [100  60  13  19]

y = [ 2 60 14]

w =  [60 50 17 23]
The unique elements in X are: [  0   2   3   4  10  12  13  14  15  17  18  19  20  22  23  24  50  60
 100]


In [144]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]


## splitting

In [129]:
a = np.arange(20.0).reshape(4,5)
np.vsplit(a, [-1,1,2,3])

[array([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]]),
 array([], shape=(0, 5), dtype=float64),
 array([[5., 6., 7., 8., 9.]]),
 array([[10., 11., 12., 13., 14.]]),
 array([[15., 16., 17., 18., 19.]])]

# Boolean Indexing, Set Operations, and Sorting

In [178]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

cx =X[X > 10]
print(type(cc))

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])


# We use set operations to compare intersect1d and y:
print()
print('The elements that are both in x and y:', np.intersect1d(X[X > 10],X[X <= 10]))
print('The elements that are in x that are not in y:', np.setdiff1d(X[X > 10],X[X <= 7]))
print('The elements that are in y that are not in x:', np.setdiff1d(X[X <= 7],X[X > 10]))
print('All the elements of x and y:',np.union1d(X[X > 10],X[X <= 7]))


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

<class 'numpy.ndarray'>
The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

The elements that are both in x and y: []
The elements that are in x that are not in y: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements that are in y that are not in x: [0 1 2 3 4 5 6 7]
All the elements of x and y: [ 0  1  2  3  4  5  6  7 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Sorting rank 1

In [181]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,10)

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 9  9  4 10  7  8  6  4  3  5]

Sorted x (out of place): [ 3  4  4  5  6  7  8  9  9 10]

x after sorting: [ 9  9  4 10  7  8  6  4  3  5]

x after sorting: [ 3  4  4  5  6  7  8  9  9 10]


## Sorting Rank 2

In [188]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X,0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X,1)) # axis default = 1

# We sort without specifing the axis ----->>> axis default = 0 ---->> sort rows
print()
print('X with sorted rows :\n', np.sort(X))


Original X = 
 [[ 2  6  5 10  7]
 [ 3  1  6  4  3]
 [ 2  3 10  9  5]
 [10  5  9  7  6]
 [ 7  3  8  2  4]]


X with sorted columns :
 [[ 2  1  5  2  3]
 [ 2  3  6  4  4]
 [ 3  3  8  7  5]
 [ 7  5  9  9  6]
 [10  6 10 10  7]]

X with sorted rows :
 [[ 2  5  6  7 10]
 [ 1  3  3  4  6]
 [ 2  3  5  9 10]
 [ 5  6  7  9 10]
 [ 2  3  4  7  8]]

X with sorted rows :
 [[ 2  5  6  7 10]
 [ 1  3  3  4  6]
 [ 2  3  5  9 10]
 [ 5  6  7  9 10]
 [ 2  3  4  7  8]]


# Arithmetic operations and Broadcasting

### Rank 1 ndarrays

In [192]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


### Rank 2 ndarrays

In [196]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


# statistical information about the elements in an ndarray
print()
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of

## Broadcasting

In [197]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]



In [202]:
# We create a rank 1 ndarray
x = np.array([1,2,3]).reshape(1,3)

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [[1 2 3]]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [210]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = np.zeros((4,4))+np.arange(1,5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [233]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = np.arange(('1','17'))
print(X)

TypeError: arange: scalar arguments expected instead of a tuple.

In [231]:
type(X[0,0])

numpy.str_